# Generated by Django 5.0 on 2024-01-05 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='material',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='myapp.material'),
            preserve_default=False,
        ),
    ]
