# Generated by Django 5.0 on 2024-01-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_panel_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='page_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='texture_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
