# Generated by Django 5.0 on 2024-01-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_material_page_link_material_texture_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='texture_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
