# Generated by Django 5.0 on 2024-01-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_material_texture_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='metalness',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='material',
            name='roughness',
            field=models.FloatField(default=0.5),
        ),
    ]
