# Generated by Django 5.0 on 2024-01-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_material_metalness_material_roughness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='texture_link',
            field=models.ImageField(blank=True, null=True, upload_to='textures/'),
        ),
    ]
