# Generated by Django 5.0 on 2024-01-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_material_texture_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='size_x',
            field=models.FloatField(default=2000),
        ),
        migrations.AddField(
            model_name='project',
            name='size_y',
            field=models.FloatField(default=2000),
        ),
        migrations.AddField(
            model_name='project',
            name='size_z',
            field=models.FloatField(default=2000),
        ),
    ]
