# Generated by Django 5.0 on 2024-01-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_project_size_x_project_size_y_project_size_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.IntegerField(default=16777215),
        ),
        migrations.AddField(
            model_name='material',
            name='opacity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='material',
            name='transparent',
            field=models.BooleanField(default=False),
        ),
    ]
