# Generated by Django 5.0 on 2024-01-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_material_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='clearcoat',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='clearcoatRoughness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='reflectivity',
            field=models.FloatField(default=0.2),
        ),
    ]
