# Generated by Django 5.0 on 2024-01-10 20:15

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_material_clearcoat_material_clearcoatroughness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='article',
            field=models.CharField(help_text='Артикул', max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='clearcoat',
            field=models.FloatField(default=1, help_text='Количество покрытия'),
        ),
        migrations.AlterField(
            model_name='material',
            name='clearcoatRoughness',
            field=models.FloatField(default=0, help_text='Шероховатость покрытия'),
        ),
        migrations.AlterField(
            model_name='material',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Цвет', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='material',
            name='metalness',
            field=models.FloatField(default=0.2, help_text='Коэффициент металличности'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(help_text='Наименование материала', max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='opacity',
            field=models.FloatField(default=1.0, help_text='Прозрачность материала (от 0 до 1)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='page_link',
            field=models.URLField(blank=True, help_text='Ссылка на сайт поставщика', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='reflectivity',
            field=models.FloatField(default=0.2, help_text='Коэффициент отражения (от 0 до 1)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='roughness',
            field=models.FloatField(default=0.5, help_text='Коэффициент шероховатости'),
        ),
        migrations.AlterField(
            model_name='material',
            name='texture_link',
            field=models.ImageField(blank=True, help_text='Текстура', null=True, upload_to='textures/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='transparent',
            field=models.BooleanField(default=False, help_text='Прозрачность'),
        ),
    ]
