# Generated by Django 5.0 on 2024-01-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_material_article_alter_material_clearcoat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtPos', models.CharField(max_length=255)),
                ('PositionX', models.FloatField(default=0)),
                ('PositionY', models.FloatField(default=0)),
                ('PositionZ', models.FloatField(default=0)),
                ('RotX', models.FloatField(default=0)),
                ('RotY', models.FloatField(default=0)),
                ('RotZ', models.FloatField(default=0)),
                ('RotW', models.FloatField(default=1)),
                ('Size', models.FloatField(default=0)),
                ('Length', models.FloatField(default=0)),
                ('Width', models.FloatField(default=0)),
            ],
        ),
    ]
