# Generated by Django 5.0 on 2024-01-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_artpos_size_article_rename_length_size_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
