# Generated by Django 5.0 on 2024-02-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_project_image_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='walls',
            field=models.FileField(blank=True, null=True, upload_to='walls/'),
        ),
    ]
