# Generated by Django 5.0 on 2024-02-15 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_project_walls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('position_z', models.FloatField(default=0)),
                ('rot_x', models.FloatField(default=0)),
                ('rot_y', models.FloatField(default=0)),
                ('rot_z', models.FloatField(default=0)),
                ('rot_w', models.FloatField(default=1)),
                ('pos1_x', models.FloatField()),
                ('pos1_y', models.FloatField()),
                ('pos1_z', models.FloatField()),
                ('pos2_x', models.FloatField()),
                ('pos2_y', models.FloatField()),
                ('pos2_z', models.FloatField()),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
    ]
