# Generated by Django 5.0 on 2024-03-10 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_size_project_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.block'),
        ),
    ]
