# Generated by Django 5.0 on 2024-03-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_block_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='parent',
            field=models.IntegerField(default=1),
        ),
    ]
