# Generated by Django 5.0 on 2024-03-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_block_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='depth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='width',
            field=models.FloatField(default=0.0),
        ),
    ]
