# Generated by Django 5.0 on 2024-03-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_block_depth_block_length_block_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='block',
            field=models.IntegerField(default=1),
        ),
    ]
