# Generated by Django 5.0 on 2024-03-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_panel_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='line3d',
            name='block',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='size',
            name='block',
            field=models.IntegerField(default=1),
        ),
    ]
