# Generated by Django 5.0 on 2024-03-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_line3d_block_size_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='anim_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='block',
            name='furn_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
