# Generated by Django 5.0 on 2024-03-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_block_anim_type_block_furn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='anim_axis_end_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='anim_axis_end_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='anim_axis_end_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='anim_axis_start_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='anim_axis_start_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='anim_axis_start_z',
            field=models.FloatField(default=0.0),
        ),
    ]
