# Generated by Django 5.0 on 2024-03-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_material_transmission_alter_material_clearcoat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='isNew',
            field=models.BooleanField(default=True, help_text='Новый материал?'),
        ),
        migrations.CreateModel(
            name='Fasteners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('block', models.IntegerField(default=1)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('position_z', models.FloatField(default=0)),
                ('rot_x', models.FloatField(default=0)),
                ('rot_y', models.FloatField(default=0)),
                ('rot_z', models.FloatField(default=0)),
                ('rot_w', models.FloatField(default=1)),
                ('model', models.ImageField(blank=True, null=True, upload_to='fasteners/')),
                ('page_link', models.URLField(blank=True, help_text='Ссылка на сайт поставщика', max_length=255, null=True)),
                ('material', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.material')),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
    ]
