# Generated by Django 5.0 on 2024-03-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_material_isnew_fasteners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fasteners',
            name='block',
        ),
        migrations.RemoveField(
            model_name='fasteners',
            name='project',
        ),
    ]
