# Generated by Django 5.0 on 2024-03-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_fasteners_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasteners',
            name='name',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
