# Generated by Django 5.0 on 2024-03-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_fasteners_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fasteners',
            name='model',
        ),
        migrations.AddField(
            model_name='fasteners',
            name='stl_file',
            field=models.FileField(blank=True, null=True, upload_to='fasteners/'),
        ),
    ]
