# Generated by Django 5.0 on 2024-03-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_remove_fasteners_model_fasteners_stl_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование типа материала', max_length=255)),
                ('roughness', models.FloatField(default=0.5, help_text='Степень матовости. 0 - Полностью блестящий, 1 - Полностью матовый)')),
                ('metalness', models.FloatField(default=0, help_text='Степень металлического блеска (от 0 до 1)')),
                ('transmission', models.FloatField(default=0, help_text='Прозрачность. 0 - Не прозрачный, 1 - полностью прозрачный')),
                ('opacity', models.FloatField(default=1.0, help_text='Прозрачность материала (от 0 до 1)')),
                ('clearcoat', models.FloatField(default=0, help_text='Количество покрытия')),
                ('clearcoatRoughness', models.FloatField(default=0, help_text='Шероховатость покрытия')),
                ('reflectivity', models.FloatField(default=0.2, help_text='Коэффициент отражения (от 0 до 1)')),
            ],
        ),
        migrations.RemoveField(
            model_name='material',
            name='opacity',
        ),
        migrations.RemoveField(
            model_name='material',
            name='transparent',
        ),
    ]
