# Generated by Django 5.0 on 2024-03-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_auto_20240315_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.ForeignKey(default=1, help_text='Тип материала', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='myapp.materialtype'),
        ),
    ]
