# Generated by Django 5.0 on 2024-03-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_material_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='article',
            field=models.CharField(blank=True, help_text='Артикул', max_length=255),
        ),
    ]
