# Generated by Django 5.0 on 2024-03-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_fastenertype_fasteners_fastener_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasteners',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fasteners',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fasteners/images/'),
        ),
    ]
