# Generated by Django 5.0 on 2024-03-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to='json/'),
        ),
    ]
