# Generated by Django 5.0 on 2024-03-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_alter_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtype',
            name='sorted',
            field=models.IntegerField(default=100),
        ),
    ]
